### ISSUE TITLE
log4js Import and Jest

### ISSUE THREAD

**Issue by ccarcaci** [log4js-node/log4js-node#1026]
Hello,
I have an issue in make log4js working with Jest.

I have this test:
```javascript
import eenie from 'src/eenie'

describe("Run eenie", () => {
  test('Verify if log4js get an error', () => {
    eenie()

    expect(true).toBe(true)
  })
})
```

That relies to this module:
```javascript
import { configure, getLogger } from "log4js";
const logger = getLogger();

configure({
  appenders: { cheese: { type: "file", filename: "cheese.log" } },
  categories: { default: { appenders: ["cheese"], level: "error" } }
});
logger.level = "debug";

const eenie = () => getLogger().debug('meenie')

export default eenie
```

When I run the module (through index) with the command:
```node -r ts-node/register -r tsconfig-paths/register src/index.ts```
it works (cheese.log file content):
```
[2020-06-05T10:15:23.546] [DEBUG] default - meenie
```

When I run the tests with the command:
```jest --passWithNoTests --runInBand```

I get the error:
```console
yarn run v1.19.2
$ jest --passWithNoTests --runInBand
 FAIL  test/eenie.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'name' of undefined

    > 1 | import { configure, getLogger } from "log4js";
        | ^
      2 | const logger = getLogger();
      3 | 
      4 | configure({

      at exports.fromCallback (node_modules/universalify/index.js:16:26)
      at Object.<anonymous> (src/eenie.ts:1:1)
      at Object.<anonymous> (test/eenie.test.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.693 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that the Jest runtime is not able to provide the correct setup for log4js, and the universalify library fails.

My node version is v12.11.1

The complete source code is available in this repo:
https://github.com/ccarcaci/log4js-jest-bug-ts

Thank you

**Comment by YutamaKotaro** [comment]
I have same issue.
I think this is not log4js problems, this is jest runtime error.
```
      at Object.<anonymous>.exports.fromCallback (node_modules/universalify/index.js:17:26)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/json/jsonfile.js:9:13)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/json/index.js:4:18)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/index.js:12:3)
      at Object.<anonymous> (node_modules/streamroller/lib/RollingFileWriteStream.js:2:12)
      at Object.<anonymous> (node_modules/streamroller/lib/index.js:2:27)
      at Object.<anonymous> (node_modules/log4js/lib/appenders/file.js:3:17)
      at Object.<anonymous> (node_modules/log4js/lib/appenders/index.js:17:27)
      at Object.<anonymous> (node_modules/log4js/lib/log4js.js:27:19)
```

This is my error log.
It occur by jsonfile module resolation from fs-extra in streamroller.
It seems to be occurred in code below.

```js
// node_modules/universalify/index.js
exports.fromCallback = function (fn) {
  return Object.defineProperty(function () {
    if (typeof arguments[arguments.length - 1] === 'function') fn.apply(this, arguments)
    else {
      return new Promise((resolve, reject) => {
        arguments[arguments.length] = (err, res) => {
          if (err) return reject(err)
          resolve(res)
        }
        arguments.length++
        fn.apply(this, arguments)
      })
    }
  }, 'name', { value: fn.name })
}
```
```js
// node_modules/streamroller/node_modules/fs-extra/lib/json/jsonfile.js
const u = require('universalify').fromCallback
const jsonFile = require('jsonfile') // <= In jest runtime, this module will be {};

module.exports = {
  // jsonfile exports
  readJson: u(jsonFile.readFile),
  readJsonSync: jsonFile.readFileSync,
  writeJson: u(jsonFile.writeFile),
  writeJsonSync: jsonFile.writeFileSync
}

```

But I have no good idea. My first aid is bellow.

```json
    "moduleNameMapper": {
      "jsonfile": "<rootDir>/node_modules/jsonfile"
    },
```

Add moduleNmaeMapper to jsonfile.

**Comment by YutamaKotaro** [comment]
If you have good idea, could you tell me that.

**Comment by YutamaKotaro** [comment]
Would you write this below?

```
    "moduleDirectories": [
      "<rootDir>/node_modules",
      "<rootDir>/src",
      "<rootDir>"
    ]
```

I solved this problem by this way.

**Comment by ccarcaci** [comment]
I'll try this and get back.

**Comment by ccarcaci** [comment]
> Write this like below, please.
> 
> ```
>     "moduleDirectories": [
>       "<rootDir>/node_modules",
>       "<rootDir>/src",
>       "<rootDir>"
>     ]
> ```
> 
> I solved this problem by this way.

That worked!
See this commit: https://github.com/ccarcaci/log4js-jest-bug-ts/commit/0e027e401ab2c75db2de8f67f1c5ccfe584ee6d1
I think that should be documented or fixed in next release.
Thanks a lot.
