### ISSUE TITLE
"TypeError: date[("get" + part)] is not a function" error when configure is called.

### ISSUE THREAD

**Issue by jgossett** [log4js-node/log4js-node#1071]
**Symptoms:**
The FileAppender does not support "%d{ISO8601_WITH_TZ_OFFSET_FORMAT}" pattern. The application throws the below exception on start up.

Output:
```
App threw an error during load
TypeError: date[("get" + part)] is not a function
    at datePart (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\node_modules\date-format\lib\index.js:34:67)
    at asString (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\node_modules\date-format\lib\index.js:48:22)
    at new RollingFileWriteStream (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\lib\RollingFileWriteStream.js:58:32)
    at new RollingFileStream (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\lib\RollingFileStream.js:16:5)
    at openTheStream (C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\appenders\file.js:9:18)
    at fileAppender (C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\appenders\file.js:53:16)
    at Object.configure (C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\appenders\file.js:97:10)
    at C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\appenders\index.js:80:27
    at Object.onlyOnMaster (C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\clustering.js:85:50)
    at createAppender (C:\Users\joshu\Desktop\Workspace\ease\node_modules\log4js\lib\appenders\index.js:78:21)``
 ```

Configuration:
```
configure({
  appenders: {

  // works.
  'consoleAppender': {
      type: 'console',
      ...
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },

   // fails
   'fileAppender': {
      type: 'file',
      ...
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },
  },

  categories: {
    default: {
      appenders: ['consoleAppender','fileAppender'],
      level: 'DEBUG'
    }
  }
})
```

**Comment by jgossett** [comment]
I found a work round. Replace 'ISO8601_WITH_TZ_OFFSET' with `yyyy-MM-ddThh:mm:ss.SSSO`.

```
   'fileAppender': {
      type: 'file',
      ...
      layout: {
        type: 'pattern',
        pattern: '%d{yyyy-MM-ddThh:mm:ss.SSSO}'
      }
    },
  },
```

**Comment by peteriman** [comment]
@jgossett Strange. I'm using `log4js@6.3.0` and it seems to work for the following code:

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
  'consoleAppender': {
      type: 'console',
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },
   'fileAppender': {
      type: 'file',
      filename: 'all-the-logs.log',
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },
  },
  categories: {
    default: {
      appenders: ['consoleAppender','fileAppender'],
      level: 'DEBUG'
    }
  }
});

const logger = log4js.getLogger();
logger.debug('Cheese is too ripe!');
```
```
         console: 2022-01-16T03:15:00.314+0800
all-the-logs.log: 2022-01-16T03:15:00.314+0800
```

**Comment by peteriman** [comment]
@jgossett Upon further investigation, I think you were using `log4js <6.0.0`.

> ```
> TypeError: date[("get" + part)] is not a function
>     at datePart (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\node_modules\date-format\lib\index.js:34:67)
>     at asString (C:\Users\joshu\Desktop\Workspace\ease\node_modules\streamroller\node_modules\date-format\lib\index.js:48:22)
> ```

This is because the logs only matched with `date-format <3.0.0`.
https://github.com/nomiddlename/date-format/blob/v2.1.0/lib/index.js#L33-L35
https://github.com/nomiddlename/date-format/blob/v2.1.0/lib/index.js#L48

`log4js@^6.0.0` uses `date-format@^3.0.0`. Perhaps it's time to upgrade.

**Comment by peteriman** [comment]
@jgossett I'm using `log4js@6.3.0` and the following code works:

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
  'consoleAppender': {
      type: 'console',
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },
   'fileAppender': {
      type: 'file',
      filename: 'all-the-logs.log',
      layout: {
        type: 'pattern',
        pattern: '%d{ISO8601_WITH_TZ_OFFSET}'
      }
    },
  },
  categories: {
    default: {
      appenders: ['consoleAppender','fileAppender'],
      level: 'DEBUG'
    }
  }
});

const logger = log4js.getLogger();
logger.debug('Cheese is too ripe!');
```
```
         console: 2022-01-16T03:15:00.314+0800
all-the-logs.log: 2022-01-16T03:15:00.314+0800
```
