### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by hxkuc** [log4js-node/log4js-node#1086]
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.dirname (path.js:583:5)
    at loadAppenderModule (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/appenders/index.js?:41:81)
    at createAppender (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/appenders/index.js?:63:29)
    at getAppender (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/appenders/index.js?:54:20)
    at eval (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/appenders/index.js?:100:7)
    at Array.forEach (<anonymous>)
    at setup (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/appenders/index.js?:96:33)
    at eval (webpack://zmlearn/./dist/dev/node_modules/log4js/lib/configuration.js?:46:33)
    at Array.forEach (<anonymous>)

**Comment by hxkuc** [comment]
log4js/lib/appenders/index.js?:41
(require.main && tryLoading(path.join(path.dirname(require.main.filename), type), config)

change?
(require.main && require.main.filename && tryLoading(path.join(path.dirname(require.main.filename), type), config)

**Comment by hxkuc** [comment]
https://github.com/DataDog/dd-trace-js/pull/973/files

**Comment by hxkuc** [comment]
6.3.0

**Comment by peteriman** [comment]
> log4js/lib/appenders/index.js?:41 (require.main && tryLoading(path.join(path.dirname(require.main.filename), type), config)
> 
> change? (require.main && require.main.filename && tryLoading(path.join(path.dirname(require.main.filename), type), config)

> https://github.com/DataDog/dd-trace-js/pull/973/files

Good change for defensive coding, which is similar to https://github.com/DataDog/dd-trace-js/pull/973/files.
