### ISSUE TITLE
layout is not a function error when trying to write JSON file

### ISSUE THREAD

**Issue by nimrodyanai** [log4js-node/log4js-node#1175]
I am trying to export the logs in a JSON file:
```
const appSettings = {
        log4js: {
            traceLogConfig: {
                appenders: {
                    fileAppender: { type: 'multiFile', layout: { type: 'json', separator: ',' }, base: `src/logs/name`, property: 'DATE', extension: '.json',
                    maxLogSize: 10485760, backups: 3, compress: true},
                    //consoleAppender: { type: 'console' }
                },
            categories: {
                default: { appenders: ['fileAppender'], level: 'trace'}
            }
        }
    }
};

export default appSettings;
```

And:
```
import log4js from "log4js";
log4js.configure(appSettings.log4js.traceLogConfig);
log4js.addLayout('json', jsonLayout);

const logger = log4js.getLogger("fileAppender");

logger.addContext(
  "DATE",
  `${new Date(Date.now()).toISOString().split("T")[0]
  }-${new Date().getHours()}-${new Date().getMinutes()}`
);

logger.info(`Test started at ${new Date(Date.now())}.`);
```

But am getting an error message:
```
C:\...\node_modules\log4js\lib\appenders\file.js:73
    if (!writer.write(layout(loggingEvent, timezoneOffset) + eol, "utf8")) {
                      ^

TypeError: layout is not a function
    at app (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\appenders\file.js:73:23)
    at appender (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\appenders\multiFile.js:55:7)
    at C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\log4js.js:42:21)
    at C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\clustering.js:23:26
    at Array.forEach (<anonymous>)
    at sendToListeners (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\clustering.js:23:13)
    at Object.send (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\clustering.js:89:7)
    at Logger._log (C:\Users\nyanai\Documents\GitHub\FOLIO-sync-services-users-csv\node_modules\log4js\lib\logger.js:95:16)
```

**Comment by peteriman** [comment]
```javascript
log4js.addLayout('json', jsonLayout);
```

What is the `jsonLayout`?

**Comment by peteriman** [comment]
I replaced that line with the following and it worked.

I replaced that line with this, and it worked.
```javascript
log4js.addLayout('json', function(config) {
  return function(logEvent) { return JSON.stringify(logEvent) + config.separator; }
});
```
_(src: https://log4js-node.github.io/log4js-node/layouts.html)_

**Comment by peteriman** [comment]
Are you expecting an array of objects?

**Comment by peteriman** [comment]
For the spin-off issue, `log4js` does not provide a JSON layout out-of-the-box at the moment.
The JSON layout example was meant as an example to show that it can be customised as such.

Nevertheless, are you expecting an array of objects to be in the log file?

**Comment by peteriman** [comment]
So, with regards to the original issue raised, are you still getting this error?
```
C:\...\node_modules\log4js\lib\appenders\file.js:73
    if (!writer.write(layout(loggingEvent, timezoneOffset) + eol, "utf8")) {
```

Marking as invalid unless the error still happens as per the original issue.

**Comment by nimrodyanai** [comment]
I'm not expecting, I'm just asking if that is possible, since right now each log line is treated separately.
But if there is no JSON support, I doubt it matters very much.
I'll have to find a way to do that manually.

Thank you!

**Comment by nomiddlename** [comment]
It's not really possible to make the contents of the log file a valid JSON array, since log4js doesn't know when to close the array. It used to be kind of a standard when logging JSON events to put one-per-line, sometimes with a comma at the end, so that you could then import them (if it was a small file) by `JSON.parse('[' + logFileContents + ']')` - but that might not be the case any more.

**Comment by peteriman** [comment]
@nimrodyanai I'm not sure if the following will satisfy your use case.

It will log each line as a valid JSON object into a new file.
The downside is that you will end up with a lot of log files.

```javascript
const log4js = require('log4js');

log4js.addLayout('json', function(config) {
  return function(logEvent) { return JSON.stringify(logEvent); }
});

log4js.configure({
  appenders: {
    out: { 
      type: 'file',
      filename: 'log.json', 
      keepFileExt: true,
      maxLogSize: 1,
      numBackups: 1000,
      layout: { type: 'json' }
    }
  },
  categories: {
    default: { appenders: ['out'], level: 'info' }
  }
});

const logger = log4js.getLogger('json-test');
logger.info('this is just a test');
logger.error('of a custom appender');
logger.warn('that outputs json');
log4js.shutdown(() => {});
```
