### ISSUE TITLE
cluster mode get TypeError: $parse(...).map is not a function

### ISSUE THREAD

**Issue by huangminlinux** [log4js-node/log4js-node#1381]
I am use log4js  "version": "6.8.0" running in pm2 cluster mode;
when i log some thing and get a error like that
```
 [ERROR] log4js - Unable to parse log: {"startTime":"2023-03-10T03:28:33.412Z"} because:  TypeError: $parse(...).map is not a function
0|api-c1  |     at Object.parse (/home/ubuntu/qin-server/node_modules/flatted/cjs/index.js:56:42)
0|api-c1  |     at Function.deserialise (/home/ubuntu/qin-server/node_modules/log4js/lib/LoggingEvent.js:115:39)
0|api-c1  |     at process.receiver (/home/ubuntu/qin-server/node_modules/log4js/lib/clustering.js:39:35)
0|api-c1  |     at process.emit (node:events:538:35)
0|api-c1  |     at emit (node:internal/child_process:938:14)
0|api-c1  |     at processTicksAndRejections (node:internal/process/task_queues:84:21)
0|api-c1  | flatted/cls parse {"startTime":"2023-03-10T03:28:33.412Z","categoryName":"default","data":["WX Helper initialized."],"level":{"level":10000,"levelStr":"DEBUG","colour":"cyan"},"context":{},"pid":13697,"cluster":{"workerId":533,"worker":13697}}
```

**Comment by lamweili** [comment]
Help me to narrow down the cause. 

1. Was it working in a previous version of `log4js`? If so, which version?

2. Is it still happening in `log4js@6.9.1`?

**Comment by lamweili** [comment]
I'm unable to replicate it. Did you serialise from elsewhere (not `log4js`) and use `log4js` to deserialise?

Based on the last line of your logs:
```js
{"startTime":"2023-03-10T03:28:33.412Z","categoryName":"default","data":["WX Helper initialized."],"level":{"level":10000,"levelStr":"DEBUG","colour":"cyan"},"context":{},"pid":13697,"cluster":{"workerId":533,"worker":13697}}
```

I've tried to create the exact same `LoggingEvent`.


```js
// original from logs
const output = '{"startTime":"2023-03-10T03:28:33.412Z","categoryName":"default","data":["WX Helper initialized."],"level":{"level":10000,"levelStr":"DEBUG","colour":"cyan"},"context":{},"pid":13697,"cluster":{"workerId":533,"worker":13697}}';

// minimum dependencies
const LoggingEvent = require('log4js/lib/LoggingEvent');
const Levels = require('log4js/lib/levels');

// creating identical LoggingEvent
let event = new LoggingEvent("default", Levels.DEBUG, ["WX Helper initialized."]);
event.startTime = new Date("2023-03-10T03:28:33.412Z");
event.pid = 13697;
event.cluster = { "workerId":533, "worker":13697 };

// check equality
assert.strictEqual(JSON.stringify(event), output); // no error thrown === same

// can be serialised and deserialised without problem
let serialised = event.serialise();
console.log(LoggingEvent.deserialise(serialised)); // no error

// if it is custom serialised, it cannot be deserialised properly
let customSerialised = '{"startTime":"2023-03-10T03:28:33.412Z"}';
console.log(LoggingEvent.deserialise(customSerialised)); // exact same error as posted
```

**Comment by lamweili** [comment]
@huangminlinux?

**Comment by lamweili** [comment]
@huangminlinux, Any updates?

**Comment by lamweili** [comment]
@huangminlinux, any updates?

**Comment by lamweili** [comment]
@huangminlinux, any updates?

**Comment by lamweili** [comment]
@huangminlinux, any updates?

**Comment by huangminlinux** [comment]
The issue has been resolved. The introduction of a third-party library caused the 'serialize' method to be replaced with an older version of log4js.
