### ISSUE TITLE
Here has an error and I can not fix it, need help

### ISSUE THREAD

**Issue by coder-free** [log4js-node/log4js-node#1382]
node version: `v18.15.0`

log4js version: `log4js@6.9.1`

my code is ( logger.ts ):
```
import log4js from 'log4js';

const config = {
    appenders: {
        debug: {
            type: 'console',
        },
        info: {
            type: 'dateFile',
            filename: 'logs/info',
            pattern: '-yyyy-MM-dd.log',
        },
        //错误日志 type:过滤类型logLevelFilter,将过滤error日志写进指定文件
        errorLog: {
            type: 'dateFile',
            filename: 'logs/error',
            pattern: '-yyyy-MM-dd.log',
        },
        error: { type: 'logLevelFilter', level: 'error', appender: 'errorLog' },
    },
    categories: {
        default: { appenders: ['debug', 'info', 'error'], level: 'debug' },
        info: { appenders: ['info', 'error'], level: 'info' },
    },
};

log4js.configure(config);

export default log4js;

```

usage:
```
import log4js from './log/logger';

const logger = log4js.getLogger('info');

logger.debug('这是一个测试日志');

```

error is:
```
[9:50:47 AM] Starting compilation in watch mode...

[9:50:49 AM] Found 0 errors. Watching for file changes.


/Users/zbf/Desktop/xl/nodejs/nest-test/src/log/logger.ts:27
log4js.configure(config);
       ^
TypeError: Cannot read properties of undefined (reading 'configure')
    at Object.<anonymous> (/Users/zbf/Desktop/xl/nodejs/nest-test/src/log/logger.ts:27:8)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/zbf/Desktop/xl/nodejs/nest-test/src/main.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
```

**Comment by lamweili** [comment]
Change 
```ts
import log4js from 'log4js';
```
To:
```ts
import * as log4js from 'log4js';
```

**Comment by lamweili** [comment]
Change 
```ts
import log4js from 'log4js';
```
To:
```ts
import * as log4js from 'log4js';
```

_(source: https://github.com/log4js-node/log4js-node#typescript)_

**Comment by lamweili** [comment]
Change 
```ts
import log4js from 'log4js';
```
To:
```ts
import * as log4js from 'log4js';
```

_(source: https://github.com/log4js-node/log4js-node#typescript)_

Please close this issue if it is resolved. Thanks!

**Comment by coder-free** [comment]
It is resolved. Thanks!
