### ISSUE TITLE
TypeError: appenderModule.configure is not a function

### ISSUE THREAD

**Issue by Wrightlt** [log4js-node/log4js-node#1411]
Node.js: v16.16.0   Nuxt: 2.15.8   log4js: 6.9.1

Hi.

I am triying to use log4js in Nuxt，it is work, but it's throwing an error: TypeError: appenderModule.configure is not a function.

this is my log4js.js:
`// const log4js = require("log4js");
// import log4js from 'log4js';
import * as log4js from "log4js";

const config = {
    appenders: {
        info: {
            info: { type: "file", filename: "logs/info.log" },
        },
    },
    categories: {
        default: { appenders: ['debug', 'info', 'error'], level: 'info' },
    },
};
log4js.configure(config);

export default log4js;`

I tried three different approaches:
Approach 1: const log4js = require("log4js");
Approach 2: import log4js from 'log4js';
Approach 3: import * as log4js from "log4js";
But all of them resulted in the above-mentioned error.

usage:
`<template>
    <div>ttt6666888</div>
</template>

<script>
import log4js from './log4js';

export default {
    name: "IndexPage",
    asyncData() {

      const logger = log4js.getLogger('info');
      logger.info('info~~~');

        return {
          test: 111
        }
    }
}
</script>
`

error is:
`TypeError: appenderModule.configure is not a function
    at eval (index.js:117:29)
    at Object.onlyOnMaster (clusteringBrowser.js:13:50)
    at createAppender (index.js:112:21)
    at getAppender (index.js:68:20)
    at eval (index.js:147:7)
    at Array.forEach (<anonymous>)
    at setup (index.js:139:33)
    at eval (configuration.js:51:35)
    at Array.forEach (<anonymous>)
    at Object.configure (configuration.js:51:13)`
    
    
    
But when I directly use log4js in a component, it works and doesn't throw an error.
my component:
`
<template>
    <div>test11</div>
</template>

<script>
const log4js = require("log4js")

export default {
    name: "IndexPage",
    asyncData() {
        log4js.configure({
            appenders: {
                out: { type: "stdout" },
                app: { type: "file", filename: "logs/app.log" }
            },
            categories: {
                default: { appenders: ["out", "app"], level: "debug" }
            }
        })
        const logger = log4js.getLogger("cheese")

        logger.info("Cheese is Comté.")
        logger.error("Cheese is too ripe!")
    }
}
</script>

`
    
    
    Do you have any solutions for this error?

**Comment by SokolovskyAlex** [comment]
hi! i have the same issue with log4js in Nuxt 3. Can anybody help with this?

**Comment by worker24h** [comment]
hi! i have the same issue with log4js in vue3 and electron.

```
import log4js from "log4js";

export default {
  install: (app, options) => {
    const logConfig = {
      appenders: {
        dateFileLog: {
          category: "log_date",
          type: "dateFile",
          filename: "./logs/log",
          alwaysIncludePattern: true,
          keepFileExt: true,
          pattern: "yyyy-MM-dd.log",
        },
        allFileLog: {
          type: "file",
          filename: "./logs/log.log",
          keepFileExt: true,
          maxLogSize: 1024 * 1024 * 100,
          backups: 3,
        },
      },
      categories: {
        default: { appenders: ["dateFileLog"], level: "info" },
        allFile: { appenders: ["allFileLog"], level: "debug" },
      },
    };
    log4js.configure(logConfig);
    app.config.globalProperties.$logger = log4js.getLogger();
  },
};
```

Error Message:
```
Uncaught TypeError: require$$1.inspect is not a function
    at createAppender (index-_dcK43Xt.js:7446:46)
    at getAppender (index-_dcK43Xt.js:7408:21)
    at index-_dcK43Xt.js:7477:7
    at Array.forEach (<anonymous>)
    at setup (index-_dcK43Xt.js:7475:33)
    at index-_dcK43Xt.js:6458:37
    at Array.forEach (<anonymous>)
    at Object.configure$9 [as configure] (index-_dcK43Xt.js:6458:15)
    at Object.configure (index-_dcK43Xt.js:8306:17)
    at Object.install (index-_dcK43Xt.js:8405:14)
```

**Comment by worker24h** [comment]
```
    const config = {
      appenders: {
        outfile: { type: 'file', filename: 'cheese.log' },
      },
      categories: {
        default: { appenders: ['outfile'], level: 'trace' },
      },
    }
``` 
上面这种配置就会出错，然而变成这种就不会报错
```
    const config = {
      appenders: {
        console: { type: 'console' },
      },
      categories: {
        default: { appenders: ['console'], level: 'trace' },
      },
    }
```

**Comment by worker24h** [comment]
![image](https://github.com/log4js-node/log4js-node/assets/24838476/d7fa57d4-a30a-4bdc-8531-75182b4d2022)

I debug code by  vscode， I found cause. I think this question is related to Node.js' fs and path modules.

**Comment by worker24h** [comment]
Downgrade version,  < v6.8.0
