### ISSUE TITLE
Objects containing circular references fail to get logged in worker process

### ISSUE THREAD

**Issue by itaysabato** [log4js-node/log4js-node#523]
Due to the internal use of `JSON.stringify` to serialize objects, some objects fail to get logged.

There are two preconditions:
1. The object contains a circular reference.
2. The object is logged in a forked cluster process.

Self contained example (copy it to a `.js` file and run with `node`) :
```js
const log4js = require('log4js');
const cluster = require('cluster');

const logger = log4js.getLogger();
logger.level = 'info';

// Comment this block out and there would be no problem:
if (cluster.isMaster) {
    cluster.fork();
}

const circle = {};
circle.me = circle;
logger.info("Circle:", circle);

setTimeout(process.exit, 1000);
```
The object is not logged in the worker process. Instead, we get the following error:
```
[2017-08-06 12:14:54.486] [ERROR] log4js - Unable to serialise log event due to : TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at logEvent.data.map (.../node_modules/log4js/lib/log4js.js:90:32)
    at Array.map (native)
    at serialise (.../node_modules/log4js/lib/log4js.js:89:35)
    at Logger.workerDispatch [as dispatch] (.../node_modules/log4js/lib/log4js.js:142:49)
    at Logger._log (.../node_modules/log4js/lib/logger.js:89:12)
    at Logger.(anonymous function) [as error] (.../node_modules/log4js/lib/logger.js:121:14)
    at Object.<anonymous> (.../log-error.js:16:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by itaysabato** [comment]
I have renamed and edited the issue once I figured out it fails for **any object** and not just errors.

This is pretty severe, perhaps using something like [circular-json](https://www.npmjs.com/package/circular-json) for serialization should be considered.

**Comment by nomiddlename** [comment]
Circular JSON looks like the way to go, thanks for the suggestion.

**Comment by itaysabato** [comment]
@nomiddlename Thanks, I hope that will resolve the issue. As a workaround (and a possible performance improvement), is there a way to disable serialization in worker processes altogether?

In v1 I used log4js out of the box without the clustered appender and everything worked fine.

**Comment by smallpath** [comment]
+1

**Comment by nomiddlename** [comment]
This should be fixed in log4js v2.4.1 - if you could confirm, that would be great.

**Comment by itaysabato** [comment]
@nomiddlename Seems to work fine with v2.4.1 - thanks!

**Comment by nomiddlename** [comment]
Thanks for the confirmation.
