### ISSUE TITLE
Fail on Passenger + apache : cluster mode

### ISSUE THREAD

**Issue by Benoit-Vasseur** [log4js-node/log4js-node#525]
Hi,

We are using Log4js in our project. Works fine on our local machines.
However the code fails when it is run by apache + passenger.

We have this error : 
```
[Thu Aug 17 16:04:58.576485 2017] [core:notice] [pid 22350:tid 140174251092096] AH00094: Command line: '/usr/sbin/httpd -f /opt/application/wpt/current/apache246/conf/httpd.conf'
App 22494 stdout: 
App 22494 stderr: Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
App 22494 stderr:     at require (internal/module.js:20:19)
App 22494 stderr:     at Object.<anonymous> (/opt/application/Application_X/node_modules/log4js/lib/log4js.js:27:17)
App 22494 stderr:     at Module._compile (module.js:570:32)
App 22494 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 22494 stderr:     at Module.load (module.js:487:32)
App 22494 stderr:     at tryModuleLoad (module.js:446:12)
App 22494 stderr:     at Function.Module._load (module.js:438:3)
App 22494 stderr:     at Module.require (module.js:497:17)
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 22494 stderr: Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
App 22494 stderr:     at require (internal/module.js:20:19)
App 22494 stderr:     at Object.<anonymous> (/opt/application/Application_X/node_modules/log4js/lib/configuration.js:5:17)
App 22494 stderr:     at Module._compile (module.js:570:32)
App 22494 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 22494 stderr:     at Module.load (module.js:487:32)
App 22494 stderr:     at tryModuleLoad (module.js:446:12)
App 22494 stderr:     at Function.Module._load (module.js:438:3)
App 22494 stderr:     at Module.require (module.js:497:17)
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 22494 stderr: Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
App 22494 stderr:     at require (internal/module.js:20:19)
App 22494 stderr:     at Object.<anonymous> (/opt/application/Application_X/node_modules/log4js/lib/logger.js:6:17)
App 22494 stderr:     at Module._compile (module.js:570:32)
App 22494 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 22494 stderr:     at Module.load (module.js:487:32)
App 22494 stderr:     at tryModuleLoad (module.js:446:12)
App 22494 stderr:     at Function.Module._load (module.js:438:3)
App 22494 stderr:     at Module.require (module.js:497:17)
App 22494 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 22494 stderr: /opt/application/Application_X/node_modules/log4js/lib/log4js.js:142
App 22494 stderr:   process.send({ topic: 'log4js:message', data: serialise(logEvent) });
App 22494 stderr:           ^
App 22494 stderr: 
App 22494 stderr: TypeError: process.send is not a function
App 22494 stderr:     at Logger.workerDispatch [as dispatch] (/opt/application/Application_X/node_modules/log4js/lib/log4js.js:142:11)
App 22494 stderr:     at Logger._log (/opt/application/Application_X/node_modules/log4js/lib/logger.js:89:12)
App 22494 stderr:     at Logger.(anonymous function) [as info] (/opt/application/Application_X/node_modules/log4js/lib/logger.js:121:14)
App 22494 stderr:     at updateCommonElements (/opt/application/Application_X/commonElements/index.js:43:15)
App 22494 stderr:     at Object.<anonymous> (/opt/application/Application_X/server.js:49:18)
App 22494 stderr:     at Module._compile (module.js:570:32)
App 22494 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 22494 stderr:     at Module.load (module.js:487:32)
App 22494 stderr:     at tryModuleLoad (module.js:446:12)
App 22494 stderr:     at Function.Module._load (module.js:438:3)
[ 2017-08-17 16:05:49.2944 22358/7f6700147700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/application/Application_X: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 273fe4b2
  Error details saved to: /tmp/passenger-error-yOibYu.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/opt/application/Application_X/node_modules/log4js/lib/log4js.js:27:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/opt/application/Application_X/node_modules/log4js/lib/configuration.js:5:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/opt/application/Application_X/node_modules/log4js/lib/logger.js:6:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
/opt/application/Application_X/node_modules/log4js/lib/log4js.js:142
  process.send({ topic: &apos;log4js:message&apos;, data: serialise(logEvent) });
          ^

TypeError: process.send is not a function
    at Logger.workerDispatch [as dispatch] (/opt/application/Application_X/node_modules/log4js/lib/log4js.js:142:11)
    at Logger._log (/opt/application/Application_X/node_modules/log4js/lib/logger.js:89:12)
    at Logger.(anonymous function) [as info] (/opt/application/Application_X/node_modules/log4js/lib/logger.js:121:14)
    at updateCommonElements (/opt/application/Application_X/commonElements/index.js:43:15)
    at Object.&lt;anonymous&gt; (/opt/application/Application_X/server.js:49:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
</pre>
```
It is related to the cluster module :/
Do you have a solution or a workaround ?

Thank you in advance.

**Comment by nomiddlename** [comment]
A quick workaround would be use log4js version 1.1.1, since that does not use the cluster module directly. But be aware that there are large differences in configuration between 1.x an 2.x. I'll also try to come up with a fix for this issue in the meantime.

**Comment by Benoit-Vasseur** [comment]
Nice, thanks for your quick reply :)

**Comment by nomiddlename** [comment]
Will be fixed by #548

**Comment by nomiddlename** [comment]
Please give log4js v2.3.4 a try, with the "disableClustering: true" option added to your configuration. That should stop the errors you're seeing.

**Comment by sk1m** [comment]
I have similar error with cluster and passenger.
This option "disableClustering: true" solved my problem. Thank you.

**Comment by nomiddlename** [comment]
I'm going to assume that the disableClustering option will help anybody with Passenger problems, so I'm closing this.

**Comment by DanielZhu** [comment]
@nomiddlename hi, using log4js v2.4.1 in our project as well, and we also use Passenger to manager the node instances

Already configured `{disableClustering: true}` in log4js.configrue({}), but passenger still throw out the errors below:

```
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:64:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/configuration.js:11:13)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:64:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/logger.js:9:13)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:64:12)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/log4js.js:35:13)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/log4js.js:211
    cluster.removeListener(&apos;message&apos;, receiver);
            ^

TypeError: cluster.removeListener is not a function
    at configure (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/log4js.js:211:13)
    at Object.&lt;anonymous&gt; (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/log4js/lib/log4js.js:289:1)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/git.nodejs.kaufmich2.lab/branches/master/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:81:25)
</pre>

[ 2017-12-19 19:45:41.9709 7614/7fca0a3a0700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 6d2828b5. Please see earlier logs for details about the error.
```

Can I turn of the feature for cluster within log4js in v2.x.x, or do you know why those kinds of error messages still appears after add this disableClustering into the configurations...

Thank you..

**Comment by nomiddlename** [comment]
@DanielZhu Sorry for taking so long to reply, this is a bug introduced in v2.4.0 I think - you should be able to roll back to v2.3.7 and disable clustering will work.

Sorry about that.

**Comment by marcelrouw** [comment]
I'm running in to the exact same issue as @DanielZhu with v2.9.. 
I set `{disableClustering: true}` in `log4js.configrue({})`.

It looks like this next line is called even when `disableClustering: true` is set
https://github.com/log4js-node/log4js-node/blob/2c75220ae1f14576cdb0b83e61823d0a095294ef/lib/log4js.js#L215

**Comment by nomiddlename** [comment]
Sorry about that @marcelrouw - I'll try to get this fixed for the next release.

**Comment by nomiddlename** [comment]
Published to NPM in version 2.10.0

**Comment by Farjallahmed** [comment]
where to set this config "disableClustering: true" because i have the same problem

**Comment by segun-flexible** [comment]
it work for me
thanks
