### ISSUE TITLE
webpacking with `target: 'node'` bundles give path as undefined 

### ISSUE THREAD

**Issue by thomashibbard** [log4js-node/log4js-node#528]
Running a script with the target set to node when bundling with webpack produces the following error:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1345:5)
    at Configuration.loadAppenderModule (/users/me/log4jstest/dist/server.js:1669:38)
    at Configuration.createAppender (/users/me/log4jstest/dist/server.js:1674:33)
    at appenderNames.forEach (/users/me/log4jstest/dist/server.js:1717:47)
    at Array.forEach (native)
    at Configuration.set appenders [as appenders] (/users/me/log4jstest/dist/server.js:1710:19)
    at new Configuration (/users/me/log4jstest/dist/server.js:1813:20)
    at configure (/users/me/log4jstest/dist/server.js:907:12)
    at Object.<anonymous> (/users/me/log4jstest/dist/server.js:987:1)
```

I've set up [this repository](https://github.com/thomashibbard/log4js-path-error) to reproduce the issue. Running `yarn build` will compile the js file from `src` into a `dist` directory, and then error can then be seen by running `node dist/server.js`

For convenience, here's the webpack config:

```
module.exports = {
  name: "server code",
  entry: "./src/server.js",
  devtool: "cheap-module-source-map",
  output: {
    filename: "./dist/server.js"
  },
  target: "node",
  node: {
    __dirname: false
  }
}
```

NPM version: 5.3.0
Node version: 8.1.4

**Comment by jasonmc86** [comment]
+1

**Comment by nomiddlename** [comment]
I think this is due to log4js loading the appender modules dynamically, so webpack doesn't know that it needs to bundle them up. Take a look at this related issue, it may help:
https://github.com/nomiddlename/log4js-node/issues/466

**Comment by mscharley** [comment]
I'm also having issues with this in webpack. As near as I can tell, there's not really any way to fix this while you're using `require(modulePath)` instead of something like `require('appenders/' + appender)`.

**Comment by nomiddlename** [comment]
Tackle this problem as part of #610

**Comment by nomiddlename** [comment]
Version 3.x of log4js has better support for webpack. Please re-open if you still have problems.
