### ISSUE TITLE
logstashUDP appender problem with null arguments

### ISSUE THREAD

**Issue by Goofo** [log4js-node/log4js-node#545]
uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at log (/storage/server-x/game-server/node_modules/log4js/lib/appenders/logstashUDP.js:43:14)
    at appenders.forEach (/storage/server-x/game-server/node_modules/log4js/lib/log4js.js:136:5)
    at Array.forEach (<anonymous>)

**Comment by nomiddlename** [comment]
This looks like a bug in the logstashUDP appender when the second argument in a log message is null. I'm going to change the title of this issue to make that a bit clearer.

**Comment by ramicohen303** [comment]
I will take a look at this one

**Comment by ramicohen303** [comment]
Created pull request #583

**Comment by ramicohen303** [comment]
Fixed in 2.3.11, closing.
