### ISSUE TITLE
Use of const in strict mode.

### ISSUE THREAD

**Issue by BeastKiller2013** [log4js-node/log4js-node#577]
All I do is add a require and I get this:

const debug = require('debug')('log4js:main');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/spook.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I cannot find any solution online,

**Comment by ramicohen303** [comment]
Is the sample code from node,js? If so, which version? 
One thing to try is to change the require statement as follows:

const log4js = require('log4js');

Works for me with node 8.x.

**Comment by ramicohen303** [comment]
Is this issue still open?

**Comment by BeastKiller2013** [comment]
Closer it I guess. I'm the only one that has it and I decided to not use the package in my project anyways.

**Comment by nomiddlename** [comment]
Thanks for letting us know @BeastKiller2013  - sorry you couldn't get it to work for you.
