### ISSUE TITLE
lOG4JS migration

### ISSUE THREAD

**Issue by VidyEmer** [log4js-node/log4js-node#586]
/home/bot/node_modules/log4js/lib/configuration.js:38
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:38:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:36:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:195:10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:201:12)
    at Object.<anonymous> (/home/bot/site.js:10:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)

**Comment by VidyEmer** [comment]
Anybody know a fix?

**Comment by ramicohen303** [comment]
The value of appenders should be an object, not an array. It should look something like this:

appenders: {
    console: {
        type: 'console'
    }
}

**Comment by ramicohen303** [comment]
See more examples here - https://log4js-node.github.io/log4js-node/appenders.html

**Comment by nomiddlename** [comment]
There's also this handy [migration guide](https://log4js-node.github.io/log4js-node/migration-guide.html)
