### ISSUE TITLE
Synchronous File Appender throws 'Path must be a string. Received ' error

### ISSUE THREAD

**Issue by ShanthaDodmane** [log4js-node/log4js-node#676]
Here is my configuration file(log4js_config.json):
```json
{
  "appenders": {
    "out": {
      "type": "stdout"
    },
    "debug": {
      "type": "fileSync",
      "filename": "logs/debug",
      "pattern": "-yyyy-MM-dd.log",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "debug-filter": {
      "type": "logLevelFilter",
      "appender": "debug",
      "level": "debug",
      "maxLevel": "debug"
    },
    "result": {
      "type": "fileSync",
      "filename": "logs/result",
      "pattern": "-yyyy-MM-dd.log",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "result-filter": {
      "type": "logLevelFilter",
      "appender": "result",
      "level": "info",
      "maxLevel": "info"
    },
    "error": {
      "type": "fileSync",
      "filename": "logs/error",
      "pattern": "-yyyy-MM-dd.log",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "error-filter": {
      "type": "logLevelFilter",
      "appender": "error",
      "level": "error",
      "maxLevel": "error"
    },
    "default": {
      "type": "fileSync",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "warn": {
      "type": "fileSync",
      "filename": "logs/warn",
      "pattern": "-yyyy-MM-dd.log",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "warn-filter": {
      "type": "logLevelFilter",
      "appender": "warn",
      "level": "warn",
      "maxLevel": "warn"
    }
  },
  "categories": {
    "default": {
      "appenders": ["out", "default"],
      "level": "info"
    },
    "debug": {
      "appenders": ["debug", "debug-filter"],
      "level": "debug"
    },
    "result": {
      "appenders": ["out", "result-filter", "debug-filter", "error-filter", "warn-filter"],
      "level": "debug"
    },
    "error": {
      "appenders": ["error", "error-filter"],
      "level": "error"
    },
    "warn": {
      "appenders": ["warn", "warn-filter"],
      "level": "warn"
    }
  }
}
```

This is how I call the above json in nodejs file server.js:
```javascript
const log4js = require('log4js');
log4js.configure('log4js_config.json');
const log = log4js.getLogger('result');
```

On executing server.js, it throws following error:
```
shantha@Ubuntu16:~/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE$ node server.js
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:1217:5)
    at fileAppender (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:149:15)
    at Object.configure (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:199:10)
    at Configuration.createAppender (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:88:29)
    at appenderNames.forEach (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:114:47)
    at Array.forEach (<anonymous>)
    at Configuration.set appenders [as appenders] (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:107:19)
    at new Configuration (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:212:20)
    at Object.configure (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/log4js.js:205:12)
```

**Comment by nomiddlename** [comment]
You've got an appender called `default` in your config, which has a type of `fileSync` but no filename.

**Comment by ShanthaDodmane** [comment]
Updated default appender to have filename as below:
```JSON
{
  "appenders": {
    "out": {
      "type": "stdout"
    },
    "debug": {
      "type": "fileSync",
      "filename": "logs/debug",
      "pattern": "-yyyy-MM-dd",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "debug-filter": {
      "type": "logLevelFilter",
      "appender": "debug",
      "level": "debug",
      "maxLevel": "debug"
    },
    "result": {
      "type": "fileSync",
      "filename": "logs/result",
      "pattern": "-yyyy-MM-dd",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "result-filter": {
      "type": "logLevelFilter",
      "appender": "result",
      "level": "info",
      "maxLevel": "info"
    },
    "error": {
      "type": "fileSync",
      "filename": "logs/error",
      "pattern": "-yyyy-MM-dd",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "error-filter": {
      "type": "logLevelFilter",
      "appender": "error",
      "level": "error",
      "maxLevel": "error"
    },
    "default": {
      "type": "fileSync",
      "filename": "logs/defaut",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "warn": {
      "type": "fileSync",
      "filename": "logs/warn",
      "pattern": "-yyyy-MM-dd",
      "alwaysIncludePattern": true,
      "keepFileExt": true
    },
    "warn-filter": {
      "type": "logLevelFilter",
      "appender": "warn",
      "level": "warn",
      "maxLevel": "warn"
    }
  },
  "categories": {
    "default": {
      "appenders": ["out", "default"],
      "level": "info"
    },
    "debug": {
      "appenders": ["debug", "debug-filter"],
      "level": "debug"
    },
    "result": {
      "appenders": ["out", "result-filter", "debug-filter", "error-filter", "warn-filter"],
      "level": "debug"
    },
    "error": {
      "appenders": ["error", "error-filter"],
      "level": "error"
    },
    "warn": {
      "appenders": ["warn", "warn-filter"],
      "level": "warn"
    }
  }
}
```
Now it is resulting in the following error:
```
shantha@Ubuntu16:~/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE$ node server.js
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'logs/debug'
    at Object.fs.openSync (fs.js:646:18)
    at touchFile (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:17:17)
    at stream (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:167:9)
    at openTheStream (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:174:10)
    at fileAppender (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:180:19)
    at Object.configure (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/appenders/fileSync.js:199:10)
    at Configuration.createAppender (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:88:29)
    at appenderNames.forEach (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:114:47)
    at Array.forEach (<anonymous>)
    at Configuration.set appenders [as appenders] (/home/shantha/test_code/tsr-tool/tsr_analysistool_ui/tsr_analysistool_BE/node_modules/log4js/lib/configuration.js:107:19)
```
But,  if I use type of  ```dateFile```  it creates log files with the name as "debug-2018-03-05" under logs directory. Here I need the same behavior using ```fileSynch```

**Comment by nomiddlename** [comment]
I think you can get the behaviour you're looking for by using the `file` appender with the `flags` option set to `rs+` (opens the file for synchronous reading and writing).

**Comment by nomiddlename** [comment]
Closing this issue, assuming you managed to fix your problem.
