### ISSUE TITLE
TCP server unable to parse log messages

### ISSUE THREAD

**Issue by florianreinhart** [log4js-node/log4js-node#756]
I've switched to TCP server/client from the multiprocess appender and ran into an issue. The server seemingly tries to parse two concatenated log message JSON objects. This of course fails with an invalid JSON exception.

This seems to happen when sending multiple log messages in quick succession.

```
[2018-07-16T07:50:06.170] [ERROR] log4js - Unable to parse log: {"startTime":"2018-07-16T07:50:06.169Z","categoryName":"MyCategory","data":["My log message 1"],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":16}{"startTime":"2018-07-16T07:50:06.170Z","categoryName":"MyCategory","data":["My log message 2"],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":16} because:  SyntaxError: Unexpected token { in JSON at position 272
   at JSON.parse (<anonymous>)
   at Object.parse (/nodeapp/node_modules/log4js/node_modules/circular-json/build/circular-json.node.js:196:32)
   at Function.deserialise (/nodeapp/node_modules/log4js/lib/LoggingEvent.js:42:44)
   at Socket.send (/nodeapp/node_modules/log4js/lib/appenders/tcp-server.js:8:32)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12)
   at readableAddChunk (_stream_readable.js:246:13)
   at Socket.Readable.push (_stream_readable.js:208:10)
   at TCP.onread (net.js:597:20)
```

The log message JSON consists of the concatenated JSON strings

```json
{
  "startTime": "2018-07-16T07:50:06.169Z",
  "categoryName": "MyCategory",
  "data": [
    "My log message 1"
  ],
  "level": {
    "level": 20000,
    "levelStr": "INFO",
    "colour": "green"
  },
  "context": {
  },
  "pid": 16
}
```

and

```json
{
  "startTime": "2018-07-16T07:50:06.170Z",
  "categoryName": "MyCategory",
  "data": [
    "My log message 2"
  ],
  "level": {
    "level": 20000,
    "levelStr": "INFO",
    "colour": "green"
  },
  "context": {
  },
  "pid": 16
}
```

Maybe some kind of separator is needed at the end of every JSON encoded log message?

**Comment by nomiddlename** [comment]
Published to npm in version 3.0.1

**Comment by florianreinhart** [comment]
@nomiddlename Looking at the code in [tcp-server.js](https://github.com/log4js-node/log4js-node/blob/v3.0.1/lib/appenders/tcp-server.js), I think there might be a concurrency issue.

`dataSoFar` is declared globally and data from all connected clients is written to it. I think `dataSoFar` needs to be declared in `net.createServer()` callback instead. However, I might be misunderstanding something and this is a non-issue.

**Comment by florianreinhart** [comment]
I am also seeing a lot of duplicated log messages in the output.

**Comment by florianreinhart** [comment]
See issue #761 and PR #762.
