### ISSUE TITLE
TypeError: layout is not a function

### ISSUE THREAD

**Issue by shengli963** [log4js-node/log4js-node#774]
I have encountered an error message, which will recur at 0 o'clock every day.
Appenders configured in the code, like this:
config:
```
...
  "disableClustering" : true
}
```
code: 
```
addConfig = function (loggerName) {
    if(config.appenders[loggerName]) {
        return config;
    }else {
        config.appenders[loggerName] = {
              "type" : "dateFile",
              "filename" : "../logs/" + loggerName,
              "pattern" : "/yyyyMMdd/yyyyMMdd-" + process.pid + ".log",
              "layout": {
                "type": "messagePassThrough"
              },
              "compress" : false,
              "alwaysIncludePattern" : true
            };

        config.categories[loggerName] = { "appenders": [ loggerName ], "level": "info" }
    }
    return config;
};

```
error info : 

```
2018-07-24T00:00:00.006Z - info: [32m[2018-07-24T00:00:00.005] [INFO] out - [39m
2018-07-24T00:00:00.011Z - error: uncaughtException: layout is not a function date=Tue Jul 24 2018 00:00:00 GMT+0000 (UTC), 
pid=19618, uid=500, gid=500, cwd=/cwd_path/latest/server, 
execPath=/home/ec2-user/.nvm/versions/node/v8.11.1/bin/node, version=v8.11.1, 

argv=[/home/ec2-user/.nvm/versions/node/v8.11.1/bin/node, /cwd_path/latest/server/app.js, -m, server, -c, node --stack_size=4096 --max-old-space-size=4096], 

rss=119296000, heapTotal=79310848, heapUsed=63465720, external=21332811, loadavg=[0.0029296875, 0.0146484375, 0.04541015625], uptime=11532440, 

trace=[
column=19, file=/cwd_path/latest/node_modules/log4js/lib/appenders/dateFile.js, function=app, line=30, method=null, native=false, column=5, file=/cwd_path/latest/node_modules/log4js/lib/log4js.js, function=appenders.forEach, line=142, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, 
column=13, file=/cwd_path/latest/node_modules/log4js/lib/log4js.js, function=Logger.sendLogEventToAppender [as dispatch], line=141, method=sendLogEventToAppender [as dispatch], native=false, 
column=12, file=/cwd_path/latest/node_modules/log4js/lib/logger.js, function=Logger._log, line=95, method=_log, native=false, 
column=14, file=/cwd_path/latest/node_modules/log4js/lib/logger.js, function=Logger.log, line=84, method=log, native=false, 
column=36, file=/cwd_path/latest/node_modules/xxx/log4jsConf/logging.js, function=null, line=12, method=null, native=false, 
column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, 
column=16, file=/cwd_path/latest/node_modules/xxx/log4jsConf/logging.js, function=Timeout._onTimeout, line=11, method=_onTimeout, native=false, 
column=11, file=timers.js, function=ontimeout, line=482, method=null, native=false, 
column=5, file=timers.js, function=tryOnTimeout, line=317, method=null, native=false, 
column=5, file=timers.js, function=Timer.listOnTimeout, line=277, method=listOnTimeout, native=false], 

stack=[TypeError: layout is not a function,     
    at app (/cwd_path/latest/node_modules/log4js/lib/appenders/dateFile.js:30:19), 
    at appenders.forEach (/cwd_path/latest/node_modules/log4js/lib/log4js.js:142:5),     
    at Array.forEach (<anonymous>:null:null),     
    at Logger.sendLogEventToAppender [as dispatch] (/cwd_path/latest/node_modules/log4js/lib/log4js.js:141:13),     
    at Logger._log (/cwd_path/latest/node_modules/log4js/lib/logger.js:95:12),     
    at Logger.log (/cwd_path/latest/node_modules/log4js/lib/logger.js:84:14),     
    at /cwd_path/latest/node_modules/xxx/log4jsConf/logging.js:12:36,     
    at Array.forEach (<anonymous>:null:null),     
    at Timeout._onTimeout (/cwd_path/latest/node_modules/xxx/log4jsConf/logging.js:11:16),     
    at ontimeout (timers.js:482:11),     
    at tryOnTimeout (timers.js:317:5),     
    at Timer.listOnTimeout (timers.js:277:5), ]
```

**Comment by shengli963** [comment]
log4js version is 2.11

**Comment by nomiddlename** [comment]
What else happens at 0 time? Do you restart your app? Send a SIGHUP signal?

**Comment by shengli963** [comment]
My config.json file made a mistake
Layout with an empty {}

```
{
  "appenders": {
    "out": { "type": "console" },
    "info": {
      "type" : "dateFile",
      "filename" : "info.log",
      "layout": {
      },
      "compress" : true
    }
  },
  "categories": {
    "default": { "appenders": [ "out" ], "level": "info" },
    "info": { "appenders": [ "info" ], "level": "info" }
  },
  "disableClustering" : true
}
```
