### ISSUE TITLE
Problem with log4js configuration

### ISSUE THREAD

**Issue by ILOVEGITHUB3214** [log4js-node/log4js-node#777]
Hello! I always get problems when trying to run "
node examplefile.js", it gives me this exact error

> Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/var/www/Bot/BOT/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (native)
    at Object.throwExceptionIf (/var/www/Bot/BOT/node_modules/log4js/lib/configuration.js:23:9)
    at configuration.addListener (/var/www/Bot/BOT/node_modules/log4js/lib/appenders/index.js:80:17)
    at listeners.forEach.listener (/var/www/Bot/BOT/node_modules/log4js/lib/configuration.js:36:33)
    at Array.forEach (native)
    at Object.configure (/var/www/Bot/BOT/node_modules/log4js/lib/configuration.js:36:13)
    at Object.configure (/var/www/Bot/BOT/node_modules/log4js/lib/log4js.js:65:17)
    at Object.<anonymous> (/var/www/Bot/BOT/site.js:10:8)
    at Module._compile (module.js:577:32)
> 

If you have any fix for it please reply back! And i don't know where to find my configuration file as it's no where to be found

**Comment by nomiddlename** [comment]
This looks like you're using version 2.x or 3.x of log4js with a version 1.x configuration. You either need to update the config (which you can't find), or roll back the version of log4js you're using.

**Comment by ILOVEGITHUB3214** [comment]
Thanks for the reply, i will try and see if i can find something. If not i'll come back and see if you can help me out

**Comment by nomiddlename** [comment]
I'm assuming you solved your problem. Closing this issue.
