### ISSUE TITLE
layout.js util.format(...loggingEvent.data) what's the meaning of ...

### ISSUE THREAD

**Issue by zky001** [log4js-node/log4js-node#792]
when I use log4js,some problem occured like this:

return util.format(...loggingEvent.data);
                       ^^^

SyntaxError: Unexpected token ...

**Comment by zky001** [comment]
if I delete ...,then 
/log4js/lib/clustering.js:8

let disabled = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by nomiddlename** [comment]
Looks like you're using a version of node less than 6.x - log4js@3.x is not supported on those older versions. You can use an older version of log4js though (2.x works with node 4+, 1.x with even older ones). Please re-open this issue if you think this isn't the problem.
