### ISSUE TITLE
 Cannot find module 'circular-json'

### ISSUE THREAD

**Issue by WTIFS** [log4js-node/log4js-node#801]
Hi there. I'm encountering a problem with the module circular-json. The details are as follows:

```
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'circular-json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/restapi.marketing.tt/app/frontend/platform/node_modules/log4js/lib/LoggingEvent.js:1:84)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

I'm using CentOS Linux release 7.2.1511, node v11.0.0, npm v6.4.1.
I can see the circular-json under node_modules. But log4js cannot find it.
If I install circular-json manually, then it will work.
And this problem didn''t show up on my mac.
Any ideas about the problem?

**Comment by nomiddlename** [comment]
What does the `cjs/loader.js` code do? Looks like it is doing some module resolving?

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your issue. Please re-open this if you feel that log4js is doing something wrong.
