### ISSUE TITLE
it's can not work inside work-thread

### ISSUE THREAD

**Issue by yygutn** [log4js-node/log4js-node#822]
```
TypeError: process.umask is not a function
    at Function.sync (projectDir/node_modules/_mkdirp@0.5.1@mkdirp/index.js:64:34)
    at DateRollingFileStream.BaseRollingFileStream.openTheStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/BaseRollingFileStream.js:79:10)
    at DateRollingFileStream.BaseRollingFileStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/BaseRollingFileStream.js:41:8)
    at new DateRollingFileStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/DateRollingFileStream.js:44:32)
    at appender (projectDir/node_modules/_log4js@2.11.0@log4js/lib/appenders/dateFile.js:23:19)
    at Object.configure (projectDir/node_modules/_log4js@2.11.0@log4js/lib/appenders/dateFile.js:53:10)
    at Configuration.createAppender (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:95:39)
    at appenderNames.forEach (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:130:47)
    at Array.forEach (<anonymous>)
    at Configuration.set appenders [as appenders] (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:123:19)
```

**Comment by nomiddlename** [comment]
Looks like you're trying to configure log4js in the worker thread - you probably want to use the multiprocess appender in version 2.x of log4js. Version 3.x of log4js handles cluster mode a bit better.

**Comment by yygutn** [comment]
> Looks like you're trying to configure log4js in the worker thread - you probably want to use the multiprocess appender in version 2.x of log4js. Version 3.x of log4js handles cluster mode a bit better.

i tried to upgrade the log4js version with 3.0.6, but useless

**Comment by yygutn** [comment]
@nomiddlename 
the same problem happened.
```
TypeError: process.umask is not a function
    at Function.sync (projectDir/node_modules/_mkdirp@0.5.1@mkdirp/index.js:64:34)
    at DateRollingFileStream.BaseRollingFileStream.openTheStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/BaseRollingFileStream.js:79:10)
    at DateRollingFileStream.BaseRollingFileStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/BaseRollingFileStream.js:41:8)
    at new DateRollingFileStream (projectDir/node_modules/_streamroller@0.7.0@streamroller/lib/DateRollingFileStream.js:44:32)
    at appender (projectDir/node_modules/_log4js@2.11.0@log4js/lib/appenders/dateFile.js:23:19)
    at Object.configure (projectDir/node_modules/_log4js@2.11.0@log4js/lib/appenders/dateFile.js:53:10)
    at Configuration.createAppender (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:95:39)
    at appenderNames.forEach (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:130:47)
    at Array.forEach (<anonymous>)
    at Configuration.set appenders [as appenders] (projectDir/node_modules/_log4js@2.11.0@log4js/lib/configuration.js:123:19)
```

**Comment by nomiddlename** [comment]
Don't call `log4js.configure` in your worker threads if you're using 3.x, only in your master thread.

**Comment by Lyoko-Jeremie** [comment]
@nomiddlename 
hi, i got a problem.
if not call ```log4js.configure``` on work-thread, the log4js not work. it's output nothing.

**Comment by nomiddlename** [comment]
Hi @Lyoko-Jeremie - could you show me some sample code that reproduces the problem, please?

**Comment by Lyoko-Jeremie** [comment]
Hi, @nomiddlename 
i create a mini reproduce project at there : https://github.com/Lyoko-Jeremie/log4js-node-issue-822
all the code pick-up from a real production project.

you can change the flag to ```false``` on this to reproduce this issue.
https://github.com/Lyoko-Jeremie/log4js-node-issue-822/blob/2c163d7e9969e4e4bf03b893987f4dc22a281d9b/src/worker.ts#L7

**Comment by nomiddlename** [comment]
Thanks for the code - that helps. I was getting confused between cluster mode (which log4js supports) and worker_threads (which log4js does not support yet). From the looks of the documentation it would be quite a bit of work to support it. As a workaround, you have to call log4js.configure in your workers. There may be side-effects if each worker is writing to the same file - but in your case you're writing to the console, so that shouldn't be a problem.

**Comment by Lyoko-Jeremie** [comment]
@nomiddlename thank you for you help~~
i use log4js to collection log into a log center, like logstash or rabbitmq.
i think it will work well when only write to console or send to a remote server, right ?

**Comment by nomiddlename** [comment]
@Lyoko-Jeremie Yes, that should be fine.

**Comment by rijnhard** [comment]
@nomiddlename I want to bump this back onto your radar, with the `worker_threads` API stable this is now more of an issue
