### ISSUE TITLE
Appenders advanced configuration not working?

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#907]
https://log4js-node.github.io/log4js-node/appenders.html states:

> If you’ve got a custom appender of your own, or are using webpack (or some other bundler), you may find it easier to pass in the appender module in the config instead of loading from the node.js require path. Here’s an example:

```javascript
const myAppenderModule = {
  configure: (config, layouts, findAppender, levels) => { /* ...your appender config... */ }
};
log4js.configure({
  appenders: { custom: { type: myAppenderModule } },
  categories: { default: { appenders: ['custom'], level: 'debug' } }
});
```

I've tried this, and it just crashes my nodejs app. Reading https://log4js-node.github.io/log4js-node/writing-appenders.html it does not mention the above loading mechanism at all:

> Log4js checks the following places (in this order) for appenders based on the type value:
> 1. The core appenders: require('./appenders/' + type)
> 2. node_modules: require(type)
> 3. relative to the main file of your application: require(path.dirname(require.main.filename) + '/' + type)
> 4. relative to the process’ current working directory: require(process.cwd() + '/' + type)

This is the simple code I am trying to achieve this:

```javascript
  const myAppenderModule = {
    configure: (config, layouts, findAppender, levels) => loggingEvent => {
      console.log('foo');
    }
  };
  log4js.configure({
    appenders: { custom: { type: myAppenderModule } },
    categories: { default: { appenders: ['custom'], level: 'debug' } }
  });
```

**Comment by nomiddlename** [comment]
Your code works ok for me - what error are you getting?

**Comment by thernstig** [comment]
```sh
/home/myuser/code/coolproject/node_modules/log4js/lib/configuration.js:25
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})` +
      ^

Error: Problem with log4js configuration: ({ appenders: { custom: { type: { configure: [Function: configure] } } },
  categories: { default: { appenders: [ 'custom' ], level: 'debug' } } }) - appender "[object Object]" could not be loaded (error was: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object)
    at tests.forEach (/home/myuser/code/coolproject/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (<anonymous>)
    at Object.throwExceptionIf (/home/myuser/code/coolproject/node_modules/log4js/lib/configuration.js:23:9)
    at tryLoading (/home/myuser/code/coolproject/node_modules/log4js/lib/appenders/index.js:25:19)
    at loadAppenderModule (/home/myuser/code/coolproject/node_modules/log4js/lib/appenders/index.js:36:3)
    at createAppender (/home/myuser/code/coolproject/node_modules/log4js/lib/appenders/index.js:42:26)
    at Object.keys.forEach (/home/myuser/code/coolproject/node_modules/log4js/lib/appenders/index.js:73:25)
    at Array.forEach (<anonymous>)
    at setup (/home/myuser/code/coolproject/node_modules/log4js/lib/appenders/index.js:71:33)
    at listeners.forEach.listener (/home/myuser/code/coolproject/node_modules/log4js/lib/configuration.js:36:33)
```

With this code:
```javascript
const log4js = require('log4js');

const myAppenderModule = {
  configure: (config, layouts, findAppender, levels) => loggingEvent => {
    console.log('foo');
  }
};
log4js.configure({
  appenders: { custom: { type: myAppenderModule } },
  categories: { default: { appenders: ['custom'], level: 'debug' } }
});
```

With this version:
`"log4js": "3.0.6"`

**Comment by nomiddlename** [comment]
Including appender modules like that was introduced in version 4.4.0 of log4js.
