### ISSUE TITLE
How to format the log content？

### ISSUE THREAD

**Issue by Q-Angelo** [log4js-node/log4js-node#910]
How to format the log content？

```js
Error: This is a Error!
    at Object.<anonymous> (/Users/project/test.js:2:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I want the following format output. How should I do it? 

```
"Error: This is a Error!\n    at Object.<anonymous> (/Users/project/test.js:2:11)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Function.Module.runMain (module.js:693:10)\n    at startup (bootstrap_node.js:188:16)\n    at bootstrap_node.js:609:3"
```

**Comment by Q-Angelo** [comment]
Found a solution：

```js
layout: {
    type: 'pattern',
    pattern: [
        '%d{yyyy-MM-ddThh:mm:ss.SSSO}', // logDate
        '%p', // logType
        '%x{singleLine}', // logContent
        ''
    ].join('[|]'),
    tokens: {
        singleLine : function(logEvent) {
            return (logEvent.data || '').toString().replace(/\s+|[\r\n]/g, '');
        }
    }
}
```
