### ISSUE TITLE
Datefile rotate error: pattern parsed error(date-format)

### ISSUE THREAD

**Issue by alexezio** [log4js-node/log4js-node#926]
hi, I am confused about this question. I don't know if it's a bug. 
Here is my situation: I use log4js(datefile) to rotate log(default pattern), and use fluentd to parse file that transport to es.  so, In my log directory, there is xxxx.log, xxxx.log.pos, two files.  everytime log4js rotate file, it will throw a error, mention that String 'pos' can't be parsed as '.yyyy-MM-dd', and node exit.

Here is my Environment:
`node: 6.17.1`  
`log4js: 4.2.0`  

Here is my config:
```
appenders: {
                out: {
                    type: 'dateFile' , filename: './logs/node.log' , pattern: '.yyyy-MM-dd-hh',
                    layout: {
                        type: 'pattern',
                        pattern: '%d{yyyy-MM-dd hh:mm:ss.SSS} [%p] %c - %m'
                    },
                    compress: true,
                    daysToKeep: 15
                }
            }
```

Error:
```
/app/node_modules/_date-format@2.1.0@date-format/lib/index.js:168
  throw new Error(
  ^

Error: String 'pos' could not be parsed as 'yyyy-MM-dd-hh'
    at extractDateParts (/app/node_modules/_date-format@2.1.0@date-format/lib/index.js:168:9)
    at Function.parse (/app/node_modules/_date-format@2.1.0@date-format/lib/index.js:178:10)
    at _.sortBy.n (/app/node_modules/_streamroller@1.0.6@streamroller/lib/RollingFileWriteStream.js:203:24)
    at /app/node_modules/_lodash@4.17.15@lodash/lodash.js:3727:18
    at arrayMap (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:639:23)
    at /app/node_modules/_lodash@4.17.15@lodash/lodash.js:3726:24
    at /app/node_modules/_lodash@4.17.15@lodash/lodash.js:3543:27
    at /app/node_modules/_lodash@4.17.15@lodash/lodash.js:4881:15
    at baseMap (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:3542:7)
    at baseOrderBy (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:3725:20)
    at Function.<anonymous> (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:9939:14)
    at apply (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:475:27)
    at Function.sortBy (/app/node_modules/_lodash@4.17.15@lodash/lodash.js:6563:16)
    at fs.readdir (/app/node_modules/_streamroller@1.0.6@streamroller/lib/RollingFileWriteStream.js:199:11)
    at go$readdir$cb (/app/node_modules/_graceful-fs@4.2.1@graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Directory details:
```
[root@consul-node2 misrobot-web-node]# ll
total 8
-rw-r--r-- 1 root root 3866 Aug  8 10:05 node.log
-rw-r--r-- 1 root root 2832 Aug  8 10:05 node.log.2019-08-06-11.gz
-rw-r--r-- 1 root root    0 Aug  8 10:26 node.log.pos
```
Here is my guess:
  I am newbee to js.  I can't understand source code, I think log4js use regex to match file. and parse the suffix as pattern. so I get a error.
  
  In log4j, I do the same thing, but it works good.

Much appreciated for any help!

**Comment by nomiddlename** [comment]
Yes, this is a bug - you're not doing anything wrong. Log4js should just ignore the `node.log.pos` file. It will be fixed in version 5 of log4js (soon), but if you want a workaround then you could try downgrading your log4js version to 3.x?

**Comment by alexezio** [comment]
Great~
I downgrade log4js from 4.2.0 to 3.0.6.  The problem no longer happened.
Appreciate for your quick response!
