### ISSUE TITLE
issue when upgrading to log4js 5.1 

### ISSUE THREAD

**Issue by maherfayez** [log4js-node/log4js-node#941]
Dears, 

once upgrading when using a root everything is fine but with another user we face the following issue 
/node_modules/streamroller/lib/RollingFileWriteStream.js:133
  async _shouldRoll() {
        ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/folders/exe/xml_interface/node_modules/streamroller/lib/index.js:2:27)
[ansadmin@ip-192-168-74-43 xml_interface]$ sudo node server.js
/folders/exe/xml_interface/node_modules/streamroller/lib/RollingFileWriteStream.js:133
  async _shouldRoll() {
        ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)

**Comment by MuhammadShaban** [comment]
it's an issue with node version 6 try to upgrade to version 8 or 10

**Comment by nomiddlename** [comment]
Closing this one, log4js@5.x needs node 8 or higher.

**Comment by lomolife** [comment]
i try upgrade node version to 8.11.1 and not work...
